language: go

go:
  - "1.10"

env:
  - PGDB=10
  - PGDB=9.6

before_install:
  - sudo -E service postgresql stop 9.2
  - sudo -E service postgresql stop 9.3
  - sudo -E service postgresql stop 9.4
  - sudo -E service postgresql stop 9.5
  - sudo -E service postgresql stop 9.6
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-$PGDB postgresql-client-$PGDB
  - sudo -E sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo -E sed -i 's/port = 5433/port = 5432/' /etc/postgresql/*/main/postgresql.conf
  - sudo -E service postgresql restart $PGDB
  # install elastic search
  - ES_VERSION=6.3.1
  - wget -q https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - sleep 10

before_script:
  - psql -U postgres -c "CREATE DATABASE elastic_test;"

script:
- go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/rp-indexer/...

after_success:
- bash <(curl -s https://codecov.io/bash)
- rm coverage.text
- rm elasticsearch-6.2.3.deb
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash

